name: medstreak
description: "A medical education game focused on mastering blood test values."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.9
  lottie: ^3.0.0
  google_fonts: ^6.1.0
  cached_network_image: ^3.3.1
  flutter_animate: ^4.5.0
  shimmer: ^3.0.0

  # State Management
  flutter_riverpod: ^2.4.10
  riverpod_annotation: ^2.3.4

  # Navigation
  go_router: ^15.1.2

  # Firebase
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8
  firebase_storage: ^12.4.6
  firebase_analytics: ^11.4.6
  firebase_app_check: ^0.3.2+6

  # Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Utilities
  image_picker: ^1.0.7
  screenshot: ^3.0.0
  share_plus: ^7.2.1 # Downgraded to a stable version compatible with current Flutter
  url_launcher: ^6.2.4
  in_app_purchase: ^3.1.13
  intl: ^0.20.2
  http: ^1.2.0
  equatable: ^2.0.5
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  uuid: ^4.3.3
  logger: ^2.0.2+1
  flutter_dotenv: ^5.1.0
  flutter_native_splash: ^2.3.10
  package_info_plus: ^8.3.0
  device_info_plus: ^11.4.0
  google_sign_in: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.8
  riverpod_generator: ^2.3.11
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1
  mocktail: ^1.0.3
  flutter_launcher_icons: ^0.14.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    # Lottie animations
    - assets/lottie/
    # Images
    - assets/images/
    - assets/icons/
    # Config files
    - .env

  # Generate internationalization files
  generate: true
