// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDl93LxEKCP_niAOoDGEgttShPfleRecOs',
    appId: '1:1045626165931:web:75e9c1cdcefe61a73eb5ee',
    messagingSenderId: '1045626165931',
    projectId: 'medstreak-85f2b',
    authDomain: 'medstreak-85f2b.firebaseapp.com',
    storageBucket: 'medstreak-85f2b.firebasestorage.app',
    measurementId: 'G-6L7Y7DD05M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUJrKsmp8_M1X60gZ-c9pYAojFd1KPge0',
    appId: '1:1045626165931:android:e2bd99a4e500e74a3eb5ee',
    messagingSenderId: '1045626165931',
    projectId: 'medstreak-85f2b',
    storageBucket: 'medstreak-85f2b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYN3uuKwXPsqXyjzIuxuwfpHSiH4fjZzo',
    appId: '1:1045626165931:ios:4e43b79fa188b62e3eb5ee',
    messagingSenderId: '1045626165931',
    projectId: 'medstreak-85f2b',
    storageBucket: 'medstreak-85f2b.firebasestorage.app',
    iosBundleId: 'com.medstreak.medstreak',
  );
}
